/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Pretendard Variable"', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'Roboto', '"Helvetica Neue"', '"Segoe UI"', '"Apple SD Gothic Neo"', '"Noto Sans KR"', '"Malgun Gothic"', 'sans-serif'],
        serif: ['"Source Serif 4"', '"Source Serif Pro"', '"Noto Serif"', 'Georgia', 'serif'],
        kserif: ['"IBM Plex Sans KR"', '"Pretendard Variable"', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderWidth: { '3': '3px' },
      colors: {
        paper: {
          DEFAULT: 'var(--paper)',
          2: 'var(--paper-2)',
          3: 'var(--paper-3)',
        },
        ink: {
          DEFAULT: 'var(--ink)',
          2: 'var(--ink-2)',
          3: 'var(--ink-3)',
          4: 'var(--ink-4)',
          subtle: 'var(--ink-2)',
          muted: 'var(--ink-3)',
          line: 'var(--rule)',
          paper: 'var(--paper-2)',
        },
        rule: 'var(--rule)',
        'rule-strong': 'var(--rule-strong)',
        accent: 'var(--accent)',
        'accent-tint': 'var(--accent-tint)',
        'accent-rule': 'var(--accent-rule)',
        pos: 'var(--pos)',
        neg: 'var(--neg)',
        'accent-primary': {
          DEFAULT: '#1c2e5a',
          light: '#3850a0',
          dark: '#0f1d40',
        },
        'accent-secondary': {
          DEFAULT: '#1d6b4f',
          light: '#2c8a68',
          dark: '#114a36',
        },
        'accent-tertiary': {
          DEFAULT: '#7a5a1a',
          light: '#a37a2a',
          dark: '#503b10',
        },
      },
      fontSize: {
        eyebrow: ['11px', { letterSpacing: '0.14em', lineHeight: '1.2' }],
        meta: ['13px', { lineHeight: '1.4' }],
        display: ['clamp(44px, 6.4vw, 88px)', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        h1: ['clamp(32px, 4vw, 52px)', { lineHeight: '1.1', letterSpacing: '-0.025em' }],
        h2: ['clamp(24px, 2.4vw, 32px)', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
      },
      maxWidth: {
        readable: '680px',
        container: '1320px',
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            maxWidth: '680px',
            color: 'var(--ink)',
            fontFamily: 'var(--kserif)',
            fontSize: '18px',
            lineHeight: '1.85',
            wordBreak: 'keep-all',
            a: {
              color: 'var(--ink)',
              textDecoration: 'none',
              borderBottom: '1px solid var(--accent-rule)',
              transition: 'background 150ms ease, border-color 150ms ease',
            },
            'a:hover': {
              backgroundColor: 'var(--accent-tint)',
              borderBottomColor: 'var(--accent)',
            },
            h1: { fontFamily: 'var(--kserif)', fontWeight: '500', letterSpacing: '-0.025em' },
            h2: {
              fontFamily: 'var(--kserif)',
              fontWeight: '500',
              letterSpacing: '-0.02em',
              fontSize: '30px',
              marginTop: '56px',
              marginBottom: '20px',
              paddingTop: '24px',
              borderTop: '1px solid var(--rule)',
            },
            h3: {
              fontFamily: 'var(--kserif)',
              fontWeight: '600',
              letterSpacing: '-0.015em',
              fontSize: '20px',
              marginTop: '36px',
              marginBottom: '12px',
            },
            p: { marginTop: '0', marginBottom: '1.4em', textWrap: 'pretty' },
            blockquote: {
              fontWeight: '400',
              fontStyle: 'normal',
              fontFamily: 'var(--kserif)',
              borderLeftColor: 'var(--accent)',
              borderLeftWidth: '3px',
              color: 'var(--ink)',
              marginTop: '32px',
              marginBottom: '32px',
              backgroundColor: 'var(--accent-tint)',
              padding: '20px 24px',
            },
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:last-of-type::after': { content: 'none' },
            strong: { color: 'var(--ink)', fontWeight: '600' },
            code: {
              color: 'var(--ink)',
              backgroundColor: 'var(--paper-2)',
              padding: '2px 6px',
              borderRadius: '0',
              border: '1px solid var(--rule)',
              fontWeight: '500',
              fontSize: '0.92em',
              fontFamily: 'var(--mono)',
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            table: { fontSize: '14px', fontFamily: 'var(--sans)' },
            'thead th': {
              borderBottomColor: 'var(--ink)',
              borderBottomWidth: '1px',
              fontFamily: 'var(--mono)',
              fontSize: '10px',
              letterSpacing: '0.14em',
              textTransform: 'uppercase',
              color: 'var(--ink-3)',
              fontWeight: '500',
            },
            'tbody tr': { borderBottomColor: 'var(--rule)' },
            hr: { borderColor: 'var(--rule)', marginTop: '48px', marginBottom: '48px' },
            'ul > li::marker': { color: 'var(--ink-3)' },
            'ol > li::marker': { color: 'var(--ink-3)', fontWeight: '500' },
          },
        },
        story: {
          css: {
            maxWidth: '58ch',
            color: 'var(--ink)',
            fontFamily: 'var(--kserif)',
            fontSize: '17px',
            lineHeight: '2.1',
            wordBreak: 'keep-all',
            p: { marginTop: '2em', marginBottom: '2em' },
            'p:first-of-type': { fontSize: '17px', fontWeight: '400' },
            'p:first-of-type::first-letter': {
              float: 'left',
              fontSize: '4.5em',
              lineHeight: '0.85',
              fontWeight: '700',
              marginRight: '0.1em',
              marginTop: '0.05em',
              color: 'var(--ink)',
              fontFamily: 'var(--kserif)',
              '@media (max-width: 640px)': { fontSize: '3.5em' },
            },
            a: {
              color: 'var(--ink)',
              borderBottom: '1px solid var(--accent-rule)',
              textDecoration: 'none',
            },
            'a:hover': { backgroundColor: 'var(--accent-tint)', borderBottomColor: 'var(--accent)' },
            strong: { color: 'var(--ink)', fontWeight: '600' },
            h2: { display: 'none' },
            h3: { display: 'none' },
          },
        },
      }),
    },
  },
  plugins: [],
};
